(Source ppx)
(Cfg_str project_name res-react-intl)
(Cfg_str project_slug res-react-intl)
(Cfg_str project_description"Reason PPX that generate Ids for ReactIntl messages")
(Cfg_str syntax Reason)
(Cfg_str package_manager Esy)
(Cfg_str test_framework Rely)
(Cfg_str ci_cd Github)
(Cfg_str author_name"Simon Degraeve")
(Cfg_str github_username SimonDegraeve)
(Cfg_str npm_username simon.degraeve)