// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var $$Intl = {};

var RawIntlProvider = {};

var IntlProvider = {};

var FormattedMessage = {};

var FormattedDate = {};

var FormattedDateParts = {};

var FormattedTime = {};

var FormattedTimeParts = {};

var FormattedRelativeTime = {};

var FormattedNumber = {};

var FormattedNumberParts = {};

var FormattedPlural = {};

var FormattedList = {};

var FormattedDisplayName = {};

exports.$$Intl = $$Intl;
exports.RawIntlProvider = RawIntlProvider;
exports.IntlProvider = IntlProvider;
exports.FormattedMessage = FormattedMessage;
exports.FormattedDate = FormattedDate;
exports.FormattedDateParts = FormattedDateParts;
exports.FormattedTime = FormattedTime;
exports.FormattedTimeParts = FormattedTimeParts;
exports.FormattedRelativeTime = FormattedRelativeTime;
exports.FormattedNumber = FormattedNumber;
exports.FormattedNumberParts = FormattedNumberParts;
exports.FormattedPlural = FormattedPlural;
exports.FormattedList = FormattedList;
exports.FormattedDisplayName = FormattedDisplayName;
/* No side effect */
